include:
  - /ci/templates/docker.gitlab-ci.yml
  # - /ci/templates/deployment.gitlab-ci.yml

stages:
  - test
  - build
  - predeploy
  - deploy
  - cleanup

default:
  tags:
    - docker

docker:build:
  extends:
    - .docker:build-sha
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
      exists:
        - Dockerfile
      when: always
    - when: never

deploy:production:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: production
    ENVIRONMENT_SUBDOMAIN: ${CI_PROJECT_NAME}
    # KUBE_INGRESS_BASE_DOMAIN: example.com
  interruptible: false
  trigger:
    include:
      - project: panaxeo-public/gitlab-auto-devops-terraform
        ref: develop
        file: /ci/templates/deployment.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH == "master"'
      exists:
        - deployment/**.tf
      when: on_success
    - when: never

deploy:development:
  stage: deploy
  variables:
    ENVIRONMENT_NAME: development
    ENVIRONMENT_SUBDOMAIN: ${CI_PROJECT_NAME}.dev
    # KUBE_INGRESS_BASE_DOMAIN: example.com
  interruptible: false
  trigger:
    include:
      - project: panaxeo-public/gitlab-auto-devops-terraform
        ref: develop
        file: /ci/templates/deployment.gitlab-ci.yml
    strategy: depend
  rules:
    - if: '$CI_KUBERNETES_ACTIVE == null || $CI_KUBERNETES_ACTIVE == ""'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
      exists:
        - deployment/**.tf
      when: on_success
    - when: never
